#!/bin/bash

function print_help()
{
    echo "Gaia Package Remote Install Script:"
    echo "  -f {path}           Path of the file or directory to install."
    echo "  -u {user}           User name to login via ssh."
    echo "  -h {host}           IP of the remote host via ssh."
    echo "  -p {port}           Port of the remote host via ssh, is 22 by defualt."
}

if [ $# -eq 0 ]
then
    print_help
    exit 1
fi

path=""
user=""
host=""
port=22

while getopts ":f:u:h:p:" option
do
    case ${option} in
        f)
            path=${OPTARG};;
        u)
            user=${OPTARG};;
        h)
            host=${OPTARG};;
        p)
            port=${OPTARG};;
        *)
            echo "Unknown argument(s) encountered."
            print_help
            exit 1;;
    esac
done

file=${path##*/}

echo "Installing package ${file} to ${host}:${port}..."

echo "Uploading package..."
# Upload file to the remote host.
if [ -d ${path} ]
then 
    scp -P ${port} -r ${path} ${user}@${host}:/home/${user}/
else
    scp -P ${port} ${path} ${user}@${host}:/home/${user}/
fi
echo "Uploading done."

# Execute install script on the remote host.

echo "Executing install script on remote host..."

ssh -o StrictHostKeyChecking=no ${user}@${host} -p ${port} << end_of_ssh
	cd ./home/${user}
	GaiaInstall ${file}
	rm -rf ${file}
	exit
end_of_ssh


echo "Remote installation done."
